# Generated by Django 5.2.11 on 2026-02-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='priority',
        ),
        migrations.AddField(
            model_name='document',
            name='dept_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='dept_report',
            field=models.FileField(blank=True, null=True, upload_to='dept_reports/'),
        ),
        migrations.AddField(
            model_name='document',
            name='final_report_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sent_to_dept_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='keywords',
            field=models.TextField(help_text='Comma-separated keywords for AI routing'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Review_Required', 'Pending Admin Review'), ('In_Progress', 'With Department'), ('Dept_Reported', 'Report Submitted by Dept'), ('Completed', 'Sent to Client'), ('Declined', 'Declined')], default='Review_Required', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Dept_Admin', 'Department Admin'), ('Main_Admin', 'Main Admin')], default='Client', max_length=50),
        ),
    ]
